export const workplaceOptions = [
    { text: "新店B單元", value: "新店B單元" },
    { text: "泰山楓江", value: "泰山楓江" },
    { text: "新莊知識", value: "新莊知識" },
    { text: "新莊塭仔圳", value: "新莊塭仔圳" },
    { text: "中和灰磘", value: "中和灰磘" },
    { text: "板橋浮洲", value: "板橋浮洲" },
    { text: "五股興珍", value: "五股興珍" },
    { text: "五股擴大都計", value: "五股擴大都計" },
    { text: "蘆洲南北", value: "蘆洲南北" },
    { text: "土城彈藥庫", value: "土城彈藥庫" },
    { text: "桃園中路", value: "桃園中路" },
    { text: "桃園航空城", value: "桃園航空城" },
    { text: "台中十四期", value: "台中十四期" },
    { text: "台南商60", value: "台南商60" },
    { text: "台南草湖寮", value: "台南草湖寮" },
    { text: "內勤-信義", value: "內勤-信義" },
    { text: "內勤-長安", value: "內勤-長安" },
    { text: "內勤-新莊", value: "內勤-新莊" },
    { text: "內勤-高雄", value: "內勤-高雄" },
    { text: "內勤-高雄", value: "內勤-高雄" },
    { text: "內勤-高雄", value: "內勤-高雄" },

  ];